뷰 작업
t-lol/T-LoL_iOS pull request #4
Opened 2017-07-04 14:09 UTC by niceoasi

2017-07-04 14:16 UTC, ArLupin requested changes
일단 수정요 ㅋㅋㅋ

2017-07-04 14:16 UTC, ArLupin commented on T-LoL/T-LoL/MatchResultTableViewCell.swift
> +    @IBOutlet var resultColorBar: [UIView]?
이부분 weak가 아닌데 다로 이유가 있어요??

2017-07-04 14:16 UTC, ArLupin commented on T-LoL/T-LoL/MatchResultTableViewCell.swift
> +    @IBOutlet var skillIconImageView: [UIImageView]?
이부분도 마찬가지

2017-07-04 14:16 UTC, ArLupin commented on T-LoL/T-LoL/MatchResultTableViewCell.swift
> +    @IBOutlet var itemIconImageView: [UIImageView]?
여기도

2017-07-04 14:16 UTC, ArLupin commented on T-LoL/T-LoL/SearchResultViewController.swift
> +        let nib = UINib(nibName: "MatchResultTableViewCell", bundle: nil)
셀들을 닙으로 사용했는데 굳이 재사용안할거라면 그냥 스토리보드에 박는게 좋을거 같아요.
그리고 만약 똑같은 방식으로 재사용이 필요할경우는 뷰컨트롤러를 컨테이너 방식으로 이용해서 재사용성을 높이는게 좋아보이네요

2017-07-04 14:16 UTC, ArLupin commented on T-LoL/T-LoL/SearchResultViewController.swift
> +        present(matchDetailVC, animated: true, completion: nil)
현재 코드로 넘어가도록 작업되어있는데 이부분 스토리보드에서 segue 사용하는 방식으로 바꿔보세요.

2017-07-04 14:16 UTC, ArLupin commented on T-LoL/T-LoL/MatchDetailCollectionViewCell.swift
> +        tableView?.dataSource = self
이부분은 스토리보드에서 연결하도록 바꿔봐요

2017-07-04 14:16 UTC, ArLupin commented on T-LoL/T-LoL/MatchDetailViewController.swift
> +        flowLayout?.itemSize = CGSize(width: view.frame.width, height: view.frame.height - 28)
flowLayout 건드는부분은 다 스토리보드에서 작업해봐요

2017-07-04 14:20 UTC, niceoasi commented on T-LoL/T-LoL/MatchResultTableViewCell.swift
> +    @IBOutlet var resultColorBar: [UIView]?
outlet collection은 weak로 선언 안돼던데..??

2017-07-05 00:32 UTC, niceoasi commented on T-LoL/T-LoL/SearchResultViewController.swift
> +        present(matchDetailVC, animated: true, completion: nil)
완료

2017-07-05 00:33 UTC, niceoasi commented on T-LoL/T-LoL/MatchDetailCollectionViewCell.swift
> +        tableView?.dataSource = self
<img width="1680" alt="screen shot 2017-07-05 at 9 33 17 am" src="https://user-images.githubusercontent.com/24788733/27845013-01ae08e8-6165-11e7-9a20-13479f519f4a.png">

이거 이렇게 연결하면 되는거 아님??

2017-07-05 01:57 UTC, niceoasi commented on T-LoL/T-LoL/MatchDetailViewController.swift
> +        flowLayout?.itemSize = CGSize(width: view.frame.width, height: view.frame.height - 28)
스토리보드에서 컬렉션 뷰 셀 아이템이 오토레이아웃 안 잡혀서,

기기별로 사이즈 맞게 하려고 flowLayout 아웃렛 잡아다가 작성한건데..

스토리보드에서 셀 아이템 오토레이아웃 잡을 수 있음??

2017-07-05 02:10 UTC, niceoasi commented on T-LoL/T-LoL/SearchResultViewController.swift
> +        let nib = UINib(nibName: "MatchResultTableViewCell", bundle: nil)
오키오키!

근데 컨테이너 방식이라는게 어떤거임??

컨테이너 뷰

2017-07-08 12:58 UTC, merged